/**
 * Lightning.Pub HTTP API adapter.
 *
 * Talks to Lightning.Pub via its HTTP API (express server on port 1776).
 * Uses JWT app token for authentication.
 *
 * Lightning.Pub API reference (from proto/autogenerated/ts/express_server.ts):
 *   POST /api/app/user/add          — create sub-account
 *   POST /api/app/user/get          — get user info (balance)
 *   POST /api/app/add/invoice       — create invoice for a user
 *   POST /api/app/user/invoice/pay  — pay invoice from user balance
 *   POST /api/app/user/internal/pay — internal transfer
 */

import type { LightningAdapter } from './types.js'

export interface LightningPubConfig {
  /** Base URL of Lightning.Pub HTTP API (e.g. http://localhost:1776) */
  url: string
  /** JWT app token (signed by Lightning.Pub's jwt_secret) */
  appToken: string
}

export class LightningPubAdapter implements LightningAdapter {
  private url: string
  private appToken: string

  constructor(config: LightningPubConfig) {
    this.url = config.url.replace(/\/$/, '')
    this.appToken = config.appToken
  }

  private async rpc<T>(path: string, body: unknown): Promise<T> {
    const res = await fetch(`${this.url}${path}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.appToken}`,
      },
      body: JSON.stringify(body),
    })
    const data = await res.json() as { status?: string; reason?: string } & T
    if (data.status === 'ERROR') {
      throw new Error(data.reason || 'Lightning.Pub error')
    }
    return data
  }

  async createUser(params: { user_id: string }) {
    await this.rpc<{ identifier: string }>('/api/app/user/add', {
      identifier: params.user_id,
      balance: 0,
      fail_if_exists: false,
    })
    return { ok: true as const }
  }

  async getBalance(params: { user_id: string }) {
    const info = await this.rpc<{ info: { balance: number } }>('/api/app/user/get', {
      user_identifier: params.user_id,
    })
    return { balance_sats: info.info?.balance ?? 0 }
  }

  async createInvoice(params: { user_id: string; amount_sats: number; memo?: string }) {
    const result = await this.rpc<{ invoice: string }>('/api/app/user/add/invoice', {
      receiver_identifier: params.user_id,
      payer_identifier: params.payer_id || 'external',
      http_callback_url: '',
      invoice_req: {
        amountSats: params.amount_sats,
        memo: params.memo || `deposit ${params.amount_sats} sats`,
      },
    })
    return { bolt11: result.invoice }
  }

  async payInvoice(params: { user_id: string; bolt11: string }) {
    const result = await this.rpc<{
      preimage: string
      amount_paid: number
    }>('/api/app/user/invoice/pay', {
      user_identifier: params.user_id,
      invoice: params.bolt11,
    })
    return {
      preimage: result.preimage,
      amount_sats: result.amount_paid,
    }
  }

  async internalTransfer(params: { from_user_id: string; to_user_id: string; amount_sats: number }) {
    await this.rpc('/api/app/user/internal/pay', {
      from_user_identifier: params.from_user_id,
      to_user_identifier: params.to_user_id,
      amount: params.amount_sats,
    })
    return { ok: true as const }
  }
}
